server:
  port: 8866

spring:
  application:
    name: configserver
  profiles:
    active: native #设置使用本地配置(默认是git,可以设置：subversion(SVN)，native(本地))
  cloud:
    config:
      server:
        #如下是GIT配置
#        git:
#          uri: https://github.com/zuowj/learning-demos     # 配置git仓库的地址（最后不需要带/，否则会出现：No custom http config found for URL: XXX）
#          search-paths: config                             # git仓库地址下的相对搜索地址（可用使用通配符），可以配置多个，用,分割。可以{application}实现按应用查配置
#          username:                                             # git仓库的账号（公开仓库无需账号信息）
#          password:                                             # git仓库的密码（公开仓库无需账号信息）
#          default-label: master                             #git默认分支

        #如下是SVN配置
#        svn:
#          uri: http://svnhost:port/svn/app-config #SVN仓库地址
#          username: svnuser #SVN账号(如果没有权限可为空)
#          password: svnpassword #SVN密码(如果没有权限可为空)
#          default-label: trunk #默认SVN分支

        #如下是本地文件配置
        native:
          search-locations: classpath:/configs #配置文件存放的目录

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/